version: '2'
services:
  hello-world:
    build:
      context: .
      dockerfile: Dockerfile-dev
    image: hello-world
    command: nodemon -L --debug 
    volumes:
      - .:/app/src
    ports:
      - "3000:3000"
      - "5858:5858"
#    extra_hosts:
